### PR TITLE
Marker

### PR DESCRIPTION
**Pull request by happydasch**
added support for more markers, src: https://matplotlib.org/3.2.1/api/markers_api.html
uses y glyph (bokeh-2.1.0), if not available, y will be used as text

### CODE REVIEW

**Comment by verybadsoldier** [comment]
Please make sure to only include commits specific to the feature this PR is aimed at. Also please provide meanigful commit messages and maybe squash commits as needed.

**Comment by verybadsoldier** [comment]
Renaming the whole project in this PR might be a bit over the top, no? :)

**Comment by happydasch** [comment]
Sorry, the marker code was just this commit:

https://github.com/verybadsoldier/backtrader_plotting/commit/16cd56e0e913829fe549b0172ca0eeb418815a4d


The other stuff are changes for my needs, so I did not comment them seriously.

**Comment by happydasch** [comment]
Sorry, the marker code was just this commit:

https://github.com/verybadsoldier/backtrader_plotting/commit/16cd56e0e913829fe549b0172ca0eeb418815a4d


The other stuff are changes for my needs, so I did not comment them seriously.

**Comment by happydasch** [comment]
Also these commits:

https://github.com/verybadsoldier/backtrader_plotting/commit/e07634e15b1168f9b2bbe3f7c3dc3f1a9ab56ba3

And this one but without the CustomJS need

https://github.com/verybadsoldier/backtrader_plotting/commit/9a4cb9a8104d21b6f095ecdb90e2a76fa02ebdc5

Went into your code and it overcome me to use this for some of my projects, btw very nice work 😃

**Comment by happydasch** [comment]
This commit was fixed also a bug in tradimo theme where Text in pre fields had the same color as background: 

https://github.com/verybadsoldier/backtrader_plotting/commit/8ea2bd0cfeba0e276faaacf17a388386a65ed3ae

**Comment by happydasch** [comment]
Maybe the best thing would be a clean base, so I move all my stuff to a different branch and just provide the patches, not really sure how to handle, since I did not do any PRs yet.

**Pull request closed without merging**
