### PR TITLE
Fix #26 - Bokeh 1.0.0 compatibility

### LINKED ISSUE #26: Support for Bokeh 1.0.0
I have the 0.5 version from pypi, and the latest version of Bokeh (1.0.0).

After running the tradimo_single.py demo, I get the following error:

`AttributeError: unexpected attribute 'logo' to Figure`

This happens with both cebero.plot(b) and b.plot_result(result).

Everything works fine on 0.13.0

### PR DESCRIPTION
**Pull request by kamilgrymuza**
Not sure if this fixes all the compatibility issues but this simple change allowed me to run the examples at least.

### CODE REVIEW

**Comment by verybadsoldier** [comment]
Could you please rebase this PR to the branch `develop`? I would like to merge it for now then. Thank you.

**Comment by gshpychka** [comment]
Is there an ETA for the fix to appear in the pypi version?

**Comment by verybadsoldier** [comment]
Sorry for the delay... Quite busy currently. I will try to do it in the next couple of days

**Comment by verybadsoldier** [comment]
Released 0.5.3 which includes this fix.

**Pull request closed without merging**
