### PR TITLE
Fix for incorrect plot master resolution for indicators

### PR DESCRIPTION
**Pull request by purinda**
- Removed incorrect plotmaster resolution using `get_data_obj`.
- Cleaned up imports in tests.

### CODE REVIEW

**Comment by verybadsoldier** [comment]
Thanks for the PR. I am sorry to say but I currently cannot work on this project. But I am really planning to get back to this in a not so far future!

**Comment by jesseliu0** [comment]
@purinda 
I was trying to plot two SMAs on the same subplot with the code:
`
self.exit_slow_ma.plotinfo.plotmaster = self.exit_fast_ma
`

After commenting out the two lines, I got the error:

> Traceback (most recent call last):
>   File "fut_bktr_trend.py", line 185, in <module>
>     result = run_backtest()
>   File "fut_bktr_trend.py", line 180, in run_backtest
>     bok.plot_result(result)
>   File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 175, in plot_result
>     self.plot(s)
>   File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 398, in plot
>     self._blueprint_strategy(obj, start, end, **kwargs)
>   File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 229, in _blueprint_strategy
>     bf.plot(master, strat_clk, None)
>   File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/figure.py", line 167, in plot
>     raise Exception(f"Unsupported plot object: {type(obj)}")
> Exception: Unsupported plot object: <class 'backtrader.lineseries.LineSeriesStub'>

**Comment by purinda** [comment]
@jesseliu0 based on the logs you are passing in the wrong `LineSeries` object to the `exit_slow_ma.plotinfo.plotmaster`. So I don't believe your issue is relevant to the original issue I opened or this PR. 

But use the framework suggested way of setting the plotmaster in your code using the `plotmaster` attribute within the indicator definition, something similar to below snippet. 
```
self.exit_slow_ma = bt.indicators.SimpleMovingAverage(period=5, subplot=True, plotmaster=self.exit_fast_ma)
```

**Comment by jesseliu0** [comment]
Thank you for the comment.
I tried the way you suggested but does not work either and produced the same error. I also tried the same code with backtrader's built-in matplotlib plot and it worked.
My purpose was trying to plot two SMAs in one subplot with backtrader-plotting, which I think kindly related with the problem your PR is supposed to solve.

**Comment by purinda** [comment]
If whatever code you tried with built-in matpotlib graphing module then checkout my branch `fix/indicator-plotmaster-resolution` and try again to plot using Bokeh. The code should be interchangeable.

**Comment by jesseliu0** [comment]
@purinda  I pip installed your fix directly from GitHub, but still error:
`
Traceback (most recent call last):
  File "fut_bktr_trend_multi.py", line 335, in <module>
    result = run_backtest()
  File "fut_bktr_trend_multi.py", line 329, in run_backtest
    bok.plot_result(result)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 173, in plot_result
    self.plot(s)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 396, in plot
    self._blueprint_strategy(obj, start, end, **kwargs)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 227, in _blueprint_strategy
    bf.plot(master, strat_clk, None)
  File "/Users/jesse/Applications/miniconda3/envs/bktr/lib/python3.7/site-packages/backtrader_plotting/bokeh/figure.py", line 167, in plot
    raise Exception(f"Unsupported plot object: {type(obj)}")
Exception: Unsupported plot object: <class 'backtrader.lineseries.LineSeriesStub'>
`

**Comment by purinda** [comment]
@jesseliu0 your problem should be discussed in an issue ticket. Not under this PR.

But in any case try running the sample strategy snippet I have added in https://github.com/verybadsoldier/backtrader_plotting/issues/30 

if that doesn't throw the error you are seeing with your code, then the issue is most probably nothing to do with `backtrader_plotting` at all but in your strategy that you have coded. Let me know.

continue the discussion if you would like under https://github.com/verybadsoldier/backtrader_plotting/issues/30 or a new issue.

**Comment by jesseliu0** [comment]
Sorry, added my comment to #30 .

**Comment by verybadsoldier** [comment]
Fixed in `develop` differently. Thanks for the PR though.

**Pull request closed without merging**
