### PR TITLE
Fixed running with multiple different strategies...

### PR DESCRIPTION
**Pull request by iSevenDays**
Fixed running with multiple different strategies using StFetcher (tested custom strategy and BuyAndHold backtrader test strategy); fixed plotting in Pycharm (iplot was set by default)

Example code with running multiple strategies:
strategy_params is a dict of custom parameters:
```
            strategy_params = dict(fast=range(20, 30, 4),
                        slow=range(20, 30, 4),)
            class StFetcher(object):
                _STRATS = [] #list of dicts(key=strategy,value=kwargs)

                def __new__(cls, *args, **kwargs):
                    idx = kwargs.pop('idx')
                    (key, value), = cls._STRATS[idx].items()
                    obj = key(*args, **{**kwargs, **value})
                    return obj
            StFetcher._STRATS = [{SMACrossLongShort: strategy_params},
                                 {BuyAndHold_Buy: strategy_params}] #actually it should be an empty dict

            cerebro.optstrategy(StFetcher, idx=[0, 1])
            bo = Bokeh()
            browser = OptBrowser(bo, optimized_runs)
            browser.start(iplot=False)
```
SMAStrategy
BuyAndHold

### CODE REVIEW

**Comment by iSevenDays** [comment]
The best-case scenario would be to create multiple tables for the number of strategy types we have, but it is better done than perfect.

I needed to compare my SMA cross strategy with BuyAndHold strategy and the pull request will allow others to do the same.

**Comment by behrad-ahmadpour** [comment]
Hi 
do you have any idea why when I use two shares to plot a realistic plot (like in Pairtrading algo) sell and buy arrows only show on one of the plots?

Thanks

**Comment by quantumpacket** [comment]
@verybadsoldier is this going to be reviewed and possibly merged? :pray:

**Comment by verybadsoldier** [comment]
Sorry, I am quite busy with other projects at the moment. Tbh I don't understand what problem this PR fixes.

Also is it intended to comment out the source code printing from the meta tab?

Whats wrong with plotting in PyCharm? I used to use PyCharm myself and didn't notice that plotting didn't work.

**Comment by quantumpacket** [comment]
As of right now for me, using a version of `StFetcher` with `optstrategy()` causes the following exception when running:

```python
results = cerebro.run(maxcpus=None, runonce=False)
bo = Bokeh()
browser = OptBrowser(bo, results)
browser.start()
```

Exception:
```
Browser is launching at: http://localhost:80
INFO:bokeh.server.server:Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)
2021-07-19 20:14:58.934 | ERROR    | tornado.web:log_exception:1789 - Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):

  File "backtest.py", line 251, in <module>
    main()
    └ <function main at 0x7f23dcddae50>

  File "backtest.py", line 235, in main
    backtest(interval=interval, symbol=symbol)
    │                 │                └ Symbol(intervals=[1440, 720], name='XDG/USD', strategies=['BollingerBand', 'GoldenCross', 'SMACrossOver', 'Strategy1'])
    │                 └ 1440
    └ <function backtest at 0x7f23dcddab80>

  File "backtest.py", line 133, in backtest
    browser.start()
    │       └ <function OptBrowser.start at 0x7f23ded1eb80>
    └ <backtrader_plotting.bokeh.optbrowser.OptBrowser object at 0x7f23dc088f40>

  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 26, in start
    webapp.start(ioloop)
    │      │     └ None
    │      └ <function BokehWebapp.start at 0x7f23dee834c0>
    └ <backtrader_plotting.bokeh.bokeh_webapp.BokehWebapp object at 0x7f23dc088ac0>
  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/bokeh_webapp.py", line 42, in start
    self._run_server(make_document, ioloop=ioloop, port=self._port)
    │    │           │                     │            │    └ 80
    │    │           │                     │            └ <backtrader_plotting.bokeh.bokeh_webapp.BokehWebapp object at 0x7f23dc088ac0>
    │    │           │                     └ None
    │    │           └ <function BokehWebapp.start.<locals>.make_document at 0x7f23d7b58f70>
    │    └ <staticmethod object at 0x7f23df545b80>
    └ <backtrader_plotting.bokeh.bokeh_webapp.BokehWebapp object at 0x7f23dc088ac0>
  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/bokeh_webapp.py", line 60, in _run_server
    server.run_until_shutdown()
    │      └ <function BaseServer.run_until_shutdown at 0x7f23dee77b80>
    └ <bokeh.server.server.Server object at 0x7f23dc01a910>
  File ".venv/lib/python3.9/site-packages/bokeh/server/server.py", line 181, in run_until_shutdown
    self._loop.start()
    │    │     └ <function BaseAsyncIOLoop.start at 0x7f23d7b5cf70>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f23d7b6e6d0>
    └ <bokeh.server.server.Server object at 0x7f23dc01a910>
  File ".venv/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x7f23df278c10>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f23d7b6e6d0>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f23df27b790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f23df33c430>
    └ <Handle <TaskStepMethWrapper object at 0x7f23d7b86910>()>
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f23d7b86910>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f23d7b86910>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f23d7b86910>()>
> File ".venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
                   └ <coroutine object DocHandler.get at 0x7f23d7b220c0>
  File ".venv/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
                    │    └ <function SessionHandler.get_session at 0x7f23e73f8c10>
                    └ <bokeh.server.views.doc_handler.DocHandler object at 0x7f23d7b868b0>
  File ".venv/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
                    │    │                   │                        │           │    │        └ 'eyJzZXNzaW9uX2lkIjogImNWVUtWM01oY2FHUjBYQVFOQVJwZlZsMUZyMnRwVzRyZW1VZThucmw5MVZlIiwgInNlc3Npb25fZXhwaXJ5IjogMTYyNjc0MDM5OCwg...
                    │    │                   │                        │           │    └ HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
                    │    │                   │                        │           └ <bokeh.server.views.doc_handler.DocHandler object at 0x7f23d7b868b0>
                    │    │                   │                        └ 'cVUKV3MhcaGR0XAQNARpfVl1Fr2tpW4remUe8nrl91Ve'
                    │    │                   └ <function ApplicationContext.create_session_if_needed at 0x7f23e73f7d30>
                    │    └ <bokeh.server.contexts.ApplicationContext object at 0x7f23d7b62070>
                    └ <bokeh.server.views.doc_handler.DocHandler object at 0x7f23d7b868b0>
  File ".venv/lib/python3.9/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
    │    │            │                   └ <bokeh.document.document.Document object at 0x7f23d7b86b50>
    │    │            └ <function Application.initialize_document at 0x7f23df904160>
    │    └ <bokeh.application.application.Application object at 0x7f23dc030e20>
    └ <bokeh.server.contexts.ApplicationContext object at 0x7f23d7b62070>
  File ".venv/lib/python3.9/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
    │ │               └ <bokeh.document.document.Document object at 0x7f23d7b86b50>
    │ └ <function FunctionHandler.modify_document at 0x7f23df54a310>
    └ <bokeh.application.handlers.function.FunctionHandler object at 0x7f23dc088880>
  File ".venv/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
    │    │     └ <bokeh.document.document.Document object at 0x7f23d7b86b50>
    │    └ <function BokehWebapp.start.<locals>.make_document at 0x7f23d7b58f70>
    └ <bokeh.application.handlers.function.FunctionHandler object at 0x7f23dc088880>
  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/bokeh_webapp.py", line 39, in make_document
    model = self._model_factory_fnc(doc)
            │    │                  └ <bokeh.document.document.Document object at 0x7f23d7b86b50>
            │    └ <bound method OptBrowser.build_optresult_model of <backtrader_plotting.bokeh.optbrowser.OptBrowser object at 0x7f23dc088f40>>
            └ <backtrader_plotting.bokeh.bokeh_webapp.BokehWebapp object at 0x7f23dc088ac0>
  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 71, in build_optresult_model
    selector, selector_cds = self._build_optresult_selector(self._optresults)
                             │    │                         │    └ [[<backtrader.cerebro.OptReturn object at 0x7f23d7b62400>], [<backtrader.cerebro.OptReturn object at 0x7f23dc042f70>], [<back...
                             │    │                         └ <backtrader_plotting.bokeh.optbrowser.OptBrowser object at 0x7f23dc088f40>
                             │    └ <function OptBrowser._build_optresult_selector at 0x7f23ded1ec10>
                             └ <backtrader_plotting.bokeh.optbrowser.OptBrowser object at 0x7f23dc088f40>
  File ".venv/lib/python3.9/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 40, in _build_optresult_selector
    df = DataFrame(data_dict)
         │         └ defaultdict(<class 'list'>, {'fast': [50, 10], 'slow': [200, 30], 'order_pct': [0.95], 'ticker': ['SPY']})
         └ <class 'pandas.core.frame.DataFrame'>
  File ".venv/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          │           │     │      │              │           │         └ 'block'
          │           │     │      │              │           └ True
          │           │     │      │              └ None
          │           │     │      └ None
          │           │     └ None
          │           └ defaultdict(<class 'list'>, {'fast': [50, 10], 'slow': [200, 30], 'order_pct': [0.95], 'ticker': ['SPY']})
          └ <function dict_to_mgr at 0x7f23e14eedc0>
  File ".venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 462, in dict_to_mgr
    return arrays_to_mgr(
           └ <function arrays_to_mgr at 0x7f23e14eea60>
  File ".venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 117, in arrays_to_mgr
    index = _extract_index(arrays)
            │              └ [[50, 10], [200, 30], [0.95], ['SPY']]
            └ <function _extract_index at 0x7f23e14f60d0>
  File ".venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 623, in _extract_index
    raise ValueError("All arrays must be of the same length")

ValueError: All arrays must be of the same length
2021-07-19 20:14:58.953 | ERROR    | tornado.web:log_request:2239 - 500 GET / (127.0.0.1) 29.43ms
```

Honestly, I'm not sure if it's related to this PR. :confused:

**Pull request closed without merging**
